export enum REQUEST_URL {
  DELETE_ACCOUNT = '/dashboard/user/profile/delete',
  ADD_SHOPPING_CART_ITEM = '/dashboard/user/cart/insert-product',
  GET_SHOPPING_CART = '/dashboard/user/cart',
  GET_ORDERS = '/dashboard/user/orders/paginate',
  GET_ORDER_BY_ID = '/dashboard/user/orders',
  CANCEL_ORDER = '/dashboard/user/orders',
  REPEAT_ORDER = '/dashboard/user/orders',
  CHECK_COUPON = '/rest/coupons/check',
  GET_FAVORITES = '/dashboard/user/profile/liked/products',
  ADD_FAVORITE = '/rest/products/',
  CALC_PRODUCT = '/rest/order/products/calculate',
  CALC_PRODUCT_AUTH = '/dashboard/user/cart/calculate',
  DELETE_SHOPPING_CART = 'dashboard/user/cart/product/delete',
  DELETE_ALL_SHOPPING_CART = '/dashboard/user/cart/delete',
  PROFILE = '/dashboard/user/profile/show',
  PROFILE_UPDATE = '/dashboard/user/profile/update',
  PAYMENT_STATUS = '/dashboard/user/transactions/order/',
}
